## 应用名称
#spring.application.name=nbrlsb
#
## 应用服务 WEB 访问端口
#server.port=8844
## 数据库驱动：
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
## 数据源名称
#spring.datasource.name=defaultDataSource
## 数据库连接地址
#spring.datasource.url=jdbc:mysql://192.168.5.213:6888/blue?serverTimezone=UTC
## 数据库用户名&密码：
#spring.datasource.username=root
#spring.datasource.password=Netboat@1234



mybatis-plus:
  mapper-locations: classpath*:org/modules/**/xml/*Mapper.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: false
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true
spring:
  application:
    name: rlsb


  datasource:
    name: defaultDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.5.213:6888/rlsb_dev?serverTimezone=UTC
    username: root
    password: Netboat@1234
server:
  port: 8845
  servlet:
    context-path: /


listener:
  port1: 20000
  port2: 20001
  port3: 20002
  port4: 20003
  port5: 20004
  port6: 20005
  port7: 20006
  port8: 20007
  start: true
  cmd: 0
  secret: XXXXXXXXXXX
  ip: 192.168.128.96
  cmdPort1: 30000
  cmdPort2: 30001
  cmdPort3: 30002
  cmdPort4: 30003
  cmdPort5: 30004
  cmdPort6: 30005
  cmdPort7: 30006
  cmdPort8: 30007


    # json:  { "code": 0 ,"message": "xxxx" ,"payload":{"params": {"command":1,"secret":"123456789","ip":"192.168.128.96","port":19995 }}}